### ISSUE TITLE
Wrong msm8916 hal path

### ISSUE THREAD

**Issue by lsiem** [kiwidevs/android_device_huawei_kiwi#1]
Compilation will fail with this error:
`build/core/binary.mk:1569: error: device/huawei/kiwi/amplifier/Android.mk: audio_amplifier.msm8916: C_INCLUDES must be under the source or output directories: /hal/.
14:56:14 ckati failed with: exit status 1
`
I personally fixed it by hardcoding the path.
So i replaced this line:
`LOCAL_C_INCLUDES := \
         $(call project-path-for,qcom-audio)/hal/ \
`
with this line:
`LOCAL_C_INCLUDES := \
        hardware/qcom/audio-caf/msm8916/hal \
`

**Comment by joelh** [comment]
Send me your email address so I can give you authorship on this commit. a45d32af560e569bb866979140f70e00a38827bb
